version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: businesspilot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/businesspilot
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  celery:
    build: ./backend
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/businesspilot
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    command: celery -A app.celery worker --loglevel=info

volumes:
  postgres_data: