import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'el' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('el'); // Greek as default

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation strings
const translations = {
  el: {
    // Navigation
    'nav.dashboard': 'Κεντρική Διαχείριση',
    'nav.sales': 'Πωλήσεις',
    'nav.inventory': 'Απόθεμα',
    'nav.employees': 'Υπάλληλοι',
    'nav.marketing': 'Μάρκετινγκ',
    'nav.finance': 'Οικονομικά',
    'nav.assistant': 'Βοηθός AI',
    'nav.paperwork': 'Γραφειοκρατία',
    
    // Dashboard
    'dashboard.title': 'Κεντρική Διαχείριση',
    'dashboard.totalSales': 'Συνολικές Πωλήσεις',
    'dashboard.revenue': 'Έσοδα',
    'dashboard.averageSale': 'Μέση Πώληση',
    'dashboard.growthRate': 'Ρυθμός Ανάπτυξης',
    'dashboard.topProducts': 'Κορυφαία Προϊόντα',
    'dashboard.recentSales': 'Πρόσφατη Δραστηριότητα Πωλήσεων',
    'dashboard.lowStockAlert': 'Ειδοποίηση Χαμηλού Αποθέματος',
    'dashboard.lowStockMessage': 'προϊόντα με χαμηλό απόθεμα.',
    'dashboard.viewInventory': 'Προβολή αποθέματος',
    'dashboard.quickActions': 'Γρήγορες Ενέργειες',
    'dashboard.addSale': 'Προσθήκη Πώλησης',
    'dashboard.addProduct': 'Προσθήκη Προϊόντος',
    'dashboard.scheduleStaff': 'Προγραμματισμός Προσωπικού',
    'dashboard.viewReports': 'Προβολή Αναφορών',
    'dashboard.noSalesData': 'Δεν υπάρχουν δεδομένα πωλήσεων',
    'dashboard.noRecentActivity': 'Δεν υπάρχει πρόσφατη δραστηριότητα',
    'dashboard.unitsSold': 'μονάδες πωλήθηκαν',
    'dashboard.sales': 'πωλήσεις',
    
    // Sales
    'sales.title': 'Πωλήσεις',
    'sales.subtitle': 'Διαχειριστείτε τις συναλλαγές πωλήσεων και αναλύστε την απόδοση',
    'sales.addSale': 'Προσθήκη Πώλησης',
    'sales.refreshData': 'Ανανέωση Δεδομένων',
    'sales.from': 'Από:',
    'sales.to': 'Έως:',
    'sales.totalSales': 'Συνολικές Πωλήσεις',
    'sales.totalRevenue': 'Συνολικά Έσοδα',
    'sales.averageSale': 'Μέση Πώληση',
    'sales.growthRate': 'Ρυθμός Ανάπτυξης',
    'sales.recentSales': 'Πρόσφατες Πωλήσεις',
    'sales.updating': 'Ενημέρωση...',
    'sales.live': 'Ζωντανά',
    'sales.date': 'Ημερομηνία',
    'sales.customer': 'Πελάτης',
    'sales.items': 'Αντικείμενα',
    'sales.payment': 'Πληρωμή',
    'sales.total': 'Σύνολο',
    'sales.actions': 'Ενέργειες',
    'sales.walkInCustomer': 'Πελάτης Χωρίς Ραντεβού',
    'sales.addNewSale': 'Προσθήκη Νέας Πώλησης',
    'sales.customerName': 'Όνομα Πελάτη',
    'sales.customerEmail': 'Email Πελάτη',
    'sales.optional': 'Προαιρετικό',
    'sales.addItem': 'Προσθήκη Αντικειμένου',
    'sales.productName': 'Όνομα Προϊόντος',
    'sales.quantity': 'Ποσότητα',
    'sales.price': 'Τιμή',
    'sales.taxAmount': 'Ποσό Φόρου',
    'sales.discount': 'Έκπτωση',
    'sales.paymentMethod': 'Μέθοδος Πληρωμής',
    'sales.cash': 'Μετρητά',
    'sales.creditCard': 'Πιστωτική Κάρτα',
    'sales.debitCard': 'Χρεωστική Κάρτα',
    'sales.mobilePayment': 'Κινητή Πληρωμή',
    'sales.subtotal': 'Υποσύνολο',
    'sales.tax': 'Φόρος',
    'sales.notes': 'Σημειώσεις',
    'sales.notesPlaceholder': 'Προαιρετικές σημειώσεις για αυτή την πώληση...',
    'sales.cancel': 'Ακύρωση',
    'sales.createSale': 'Δημιουργία Πώλησης',
    'sales.creating': 'Δημιουργία...',
    'sales.saleDetails': 'Λεπτομέρειες Πώλησης',
    'sales.product': 'Προϊόν',
    'sales.qty': 'Ποσ.',
    'sales.close': 'Κλείσιμο',
    
    // Assistant
    'assistant.title': 'AI Επιχειρηματικός Βοηθός',
    'assistant.subtitle': 'Ρωτήστε με οτιδήποτε για την επιχείρησή σας',
    'assistant.welcome': 'Καλώς ήρθατε στον AI Βοηθό σας!',
    'assistant.description': 'Μπορώ να σας βοηθήσω με ανάλυση πωλήσεων, διαχείριση αποθέματος, οικονομικές πληροφορίες και άλλα.',
    'assistant.businessOverview': 'Επιχειρηματική Επισκόπηση',
    'assistant.revenue': 'Έσοδα',
    'assistant.netProfit': 'Καθαρό Κέρδος',
    'assistant.topProduct': 'Κορυφαίο Προϊόν',
    'assistant.lowStockAlerts': 'Ειδοποιήσεις Χαμηλού Στοκ',
    'assistant.typing': 'Γράφει...',
    'assistant.inputPlaceholder': 'Ρωτήστε με οτιδήποτε για την επιχείρησή σας...',
    'assistant.clearChat': 'Καθαρισμός Chat',
    'assistant.suggestedQuestions': 'Προτεινόμενες Ερωτήσεις',
    'assistant.businessInsights': 'Επιχειρηματικές Γνώσεις',
    'assistant.currentStatus': 'Τρέχουσα Κατάσταση',
    'assistant.quickStats': 'Γρήγορα Στατιστικά',
    'assistant.todayRevenue': 'Σημερινά Έσοδα',
    'assistant.activeEmployees': 'Ενεργοί Υπάλληλοι',
    'assistant.lowStockProducts': 'Προϊόντα Χαμηλού Στοκ',
    'assistant.tips': 'Συμβουλές',
    'assistant.tipText': 'Δοκιμάστε να κάνετε συγκεκριμένες ερωτήσεις όπως "Ποιο είναι το προϊόν με τις καλύτερες πωλήσεις;" ή "Πώς μπορώ να βελτιώσω το περιθώριο κέρδους;"',
    'assistant.failedToSend': 'Αποτυχία αποστολής μηνύματος',
    'assistant.failedToClear': 'Αποτυχία καθαρισμού ιστορικού συνομιλίας',
    'assistant.chatCleared': 'Το ιστορικό συνομιλίας καθαρίστηκε',
    'assistant.topSellingProducts': 'Ποια είναι τα προϊόντα με τις καλύτερες πωλήσεις;',
    'assistant.profitMargins': 'Δείξε μου το περιθώριο κέρδους',
    'assistant.salesTrends': 'Πώς είναι οι τάσεις των πωλήσεων;',
    'assistant.inventoryStatus': 'Ποια είναι η τρέχουσα κατάσταση του αποθέματος;',
    'assistant.employeeHours': 'Πόσες ώρες δούλεψαν οι υπάλληλοι;',
    'assistant.runPromotion': 'Πρέπει να τρέξω μια προσφορά;',
    'assistant.salesAnalysis': 'Ανάλυση Πωλήσεων',
    'assistant.salesAnalysisDesc': 'Δείτε τις επιδόσεις πωλήσεων',
    'assistant.salesAnalysisQuestion': 'Δείξε μου την ανάλυση πωλήσεων',
    'assistant.financialOverview': 'Οικονομική Επισκόπηση',
    'assistant.financialOverviewDesc': 'Ελέγξτε τα οικονομικά σας',
    'assistant.financialOverviewQuestion': 'Δείξε μου την οικονομική επισκόπηση',
    'assistant.inventoryCheck': 'Έλεγχος Αποθέματος',
    'assistant.inventoryCheckDesc': 'Κατάσταση αποθέματος',
    'assistant.inventoryCheckQuestion': 'Δείξε μου την κατάσταση του αποθέματος',
    'assistant.employeeMetrics': 'Μετρικές Υπαλλήλων',
    'assistant.employeeMetricsDesc': 'Επιδόσεις προσωπικού',
    'assistant.employeeMetricsQuestion': 'Δείξε μου τις μετρικές υπαλλήλων',
    'assistant.suggestion1': 'Ποια είναι τα κορυφαία προϊόντα αυτό το μήνα;',
    'assistant.suggestion2': 'Πώς μπορώ να βελτιώσω τις πωλήσεις;',
    'assistant.suggestion3': 'Τι προϊόντα χρειάζονται επαναπαραγγελία;',
    'assistant.suggestion4': 'Πώς είναι η παραγωγικότητα των υπαλλήλων;',
    'assistant.suggestion5': 'Προτείνεις κάποια στρατηγική μάρκετινγκ;',
    'assistant.assistant': 'Βοηθός',
    'assistant.suggestions': 'Προτάσεις',
    'assistant.thisMonth': 'αυτό το μήνα',
    'assistant.averageTransaction': 'Μέσος Όρος Συναλλαγής',
    'assistant.salesRecommendation': 'Συστήνω να εστιάσετε στο κορυφαίο προϊόν και να αυξήσετε το μάρκετινγκ για παρόμοια προϊόντα.',
    'assistant.financialSummary': 'Οικονομική Περίληψη',
    'assistant.profitMargin': 'Περιθώριο Κέρδους',
    'assistant.expenses': 'Έξοδα',
    'assistant.financialAdvice': 'Τα οικονομικά σας φαίνονται υγιή. Σκεφτείτε επενδύσεις για περαιτέρω ανάπτυξη.',
    'assistant.totalProducts': 'Συνολικά Προϊόντα',
    'assistant.stockValue': 'Αξία Αποθέματος',
    'assistant.reorderSoon': 'Επαναπαραγγελία Σύντομα',
    'assistant.items': 'αντικείμενα',
    'assistant.inventoryAction': 'Συστήνω να παραγγείλετε ξανά τα προϊόντα χαμηλού αποθέματος για να αποφύγετε τη διακοπή.',
    'assistant.employeeOverview': 'Επισκόπηση Υπαλλήλων',
    'assistant.activeStaff': 'Ενεργό Προσωπικό',
    'assistant.hoursWorked': 'Ώρες Εργασίας',
    'assistant.thisWeek': 'αυτή την εβδομάδα',
    'assistant.productivity': 'Παραγωγικότητα',
    'assistant.scheduleOptimization': 'Βελτιστοποίηση Προγράμματος',
    'assistant.excellent': 'Εξαιρετική',
    'assistant.employeeNote': 'Το προσωπικό σας έχει υψηλή παραγωγικότητα. Συνεχίστε τις καλές πρακτικές.',
    'assistant.helpMessage': 'Γεια! Είμαι ο AI βοηθός σας για επιχειρήσεις. Μπορώ να σας βοηθήσω με διάφορα θέματα.',
    'assistant.capabilities': 'Μπορώ να σας βοηθήσω με',
    'assistant.cap1': 'Ανάλυση πωλήσεων και τάσεων',
    'assistant.cap2': 'Οικονομική επισκόπηση και αναφορές',
    'assistant.cap3': 'Διαχείριση αποθέματος',
    'assistant.cap4': 'Μετρικές και επιδόσεις υπαλλήλων',
    'assistant.askMore': 'Ρωτήστε με οτιδήποτε για την επιχείρησή σας!',
    'assistant.pendingOrders': 'Εκκρεμείς Παραγγελίες',
    'assistant.monthlyRevenue': 'Μηνιαίο Έσοδα',
    
    // Theme and Interface
    'theme.lightMode': 'Φωτεινό Θέμα',
    'theme.darkMode': 'Σκοτεινό Θέμα',
    'theme.systemMode': 'Σύστημα',
    'interface.welcome': 'Καλώς ήρθατε',
    'interface.greeting': 'Γεια σας',
    'interface.goodMorning': 'Καλημέρα',
    'interface.goodAfternoon': 'Καλησπέρα',
    'interface.goodEvening': 'Καληνύχτα',
    'interface.poweredBy': 'Με την υποστήριξη του',
    'interface.version': 'Έκδοση',
    'interface.lastUpdated': 'Τελευταία ενημέρωση',
    'interface.goToTop': 'Πάνω',
    'interface.scrollToBottom': 'Κάτω',
    'interface.expand': 'Επέκταση',
    'interface.collapse': 'Σύμπτυξη',
    'interface.fullscreen': 'Πλήρης οθόνη',
    'interface.exitFullscreen': 'Έξοδος πλήρους οθόνης',
    
    // Paperwork Assistant
    'paperwork.title': 'Βοηθός Γραφειοκρατίας',
    'paperwork.subtitle': 'AI βοήθεια για έντυπα και διαδικασίες',
    'paperwork.welcome': 'Καλώς ήρθατε στον Βοηθό Γραφειοκρατίας!',
    'paperwork.description': 'Ρωτήστε με για έντυπα, προθεσμίες, και διαδικασίες',
    'paperwork.startBusiness': 'Έναρξη Επιχείρησης',
    'paperwork.deadlines': 'Προθεσμίες',
    'paperwork.pending': 'Εκκρεμότητες',
    'paperwork.taxes': 'Φορολογικά',
    'paperwork.documentsStatus': 'Κατάσταση Εντύπων',
    'paperwork.urgent': 'Επείγοντα',
    'paperwork.allDocuments': 'Όλα τα Έντυπα',
    'paperwork.tips': 'Συμβουλές',
    'paperwork.completed': 'Ολοκληρωμένα',
    'paperwork.overdue': 'Εκπρόθεσμα',
    'paperwork.ministry': 'Φορέας',
    'paperwork.estimatedTime': 'Εκτιμώμενος Χρόνος',
    'paperwork.deadline': 'Προθεσμία',
    'paperwork.status': 'Κατάσταση',
    'paperwork.requirements': 'Απαιτούμενα',
    'paperwork.download': 'Κατέβασμα',
    'paperwork.details': 'Λεπτομέρειες Εντύπου',
    
    // Common
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.save': 'Αποθήκευση',
    'common.cancel': 'Ακύρωση',
    'common.add': 'Προσθήκη',
    'common.edit': 'Επεξεργασία',
    'common.delete': 'Διαγραφή',
    'common.search': 'Αναζήτηση',
    'common.filter': 'Φίλτρο',
    'common.export': 'Εξαγωγή',
    'common.import': 'Εισαγωγή',
    'common.refresh': 'Ανανέωση',
    'common.back': 'Επιστροφή',
    'common.next': 'Επόμενο',
    'common.previous': 'Προηγούμενο',
    'common.close': 'Κλείσιμο',
    'common.submit': 'Υποβολή',
    'common.reset': 'Επαναφορά',
    'common.confirm': 'Επιβεβαίωση',
    'common.yes': 'Ναι',
    'common.no': 'Όχι',
    'common.name': 'Όνομα',
    'common.email': 'Email',
    'common.phone': 'Τηλέφωνο',
    'common.address': 'Διεύθυνση',
    'common.date': 'Ημερομηνία',
    'common.time': 'Ώρα',
    'common.status': 'Κατάσταση',
    'common.actions': 'Ενέργειες',
    'common.details': 'Λεπτομέρειες',
    'common.total': 'Σύνολο',
    'common.subtotal': 'Υποσύνολο',
    'common.price': 'Τιμή',
    'common.quantity': 'Ποσότητα',
    'common.category': 'Κατηγορία',
    'common.description': 'Περιγραφή',
    'common.notes': 'Σημειώσεις',
    
    // Authentication
    'auth.login': 'Σύνδεση',
    'auth.logout': 'Αποσύνδεση',
    'auth.register': 'Εγγραφή',
    'auth.signIn': 'Είσοδος',
    'auth.signUp': 'Εγγραφή',
    'auth.email': 'Διεύθυνση Email',
    'auth.password': 'Κωδικός Πρόσβασης',
    'auth.fullName': 'Πλήρες Όνομα',
    'auth.businessName': 'Όνομα Επιχείρησης',
    'auth.businessType': 'Τύπος Επιχείρησης',
    'auth.createAccount': 'Δημιουργία λογαριασμού',
    'auth.signingIn': 'Σύνδεση...',
    'auth.creatingAccount': 'Δημιουργία λογαριασμού...',
    'auth.emailRequired': 'Το email είναι υποχρεωτικό',
    'auth.passwordRequired': 'Ο κωδικός είναι υποχρεωτικός',
    'auth.fullNameRequired': 'Το πλήρες όνομα είναι υποχρεωτικό',
    'auth.businessNameRequired': 'Το όνομα επιχείρησης είναι υποχρεωτικό',
    'auth.businessTypeRequired': 'Ο τύπος επιχείρησης είναι υποχρεωτικός',
    'auth.invalidEmail': 'Μη έγκυρη διεύθυνση email',
    'auth.passwordMinLength': 'Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες',
    'auth.selectBusinessType': 'Επιλέξτε τύπο επιχείρησης',
    
    // Business Types
    'businessType.retail': 'Λιανικό Εμπόριο',
    'businessType.restaurant': 'Εστιατόριο',
    'businessType.cafe': 'Καφετέρια',
    'businessType.service': 'Υπηρεσίες',
    'businessType.healthcare': 'Υγειονομική Περίθαλψη',
    'businessType.beauty': 'Ομορφιά',
    'businessType.other': 'Άλλο',
    
    // Header
    'header.title': 'BusinessPilot AI',
    'header.subtitle': 'Η ολοκληρωμένη ομάδα AI για τις επιχειρησιακές σας δραστηριότητες',
    'header.language': 'Γλώσσα',
    'header.profile': 'Προφίλ',
    'header.settings': 'Ρυθμίσεις',
    
    // Time periods
    'time.7d': '7 ημέρες',
    'time.30d': '30 ημέρες',
    'time.90d': '90 ημέρες',
    'time.today': 'Σήμερα',
    'time.yesterday': 'Χθες',
    'time.thisWeek': 'Αυτή την εβδομάδα',
    'time.lastWeek': 'Την προηγούμενη εβδομάδα',
    'time.thisMonth': 'Αυτό το μήνα',
    'time.lastMonth': 'Τον προηγούμενο μήνα',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Central Management',
    'nav.sales': 'Sales',
    'nav.inventory': 'Inventory',
    'nav.employees': 'Employees',
    'nav.marketing': 'Marketing',
    'nav.finance': 'Finance',
    'nav.assistant': 'AI Assistant',
    'nav.paperwork': 'Paperwork',
    
    // Dashboard
    'dashboard.title': 'Central Management',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.revenue': 'Revenue',
    'dashboard.averageSale': 'Average Sale',
    'dashboard.growthRate': 'Growth Rate',
    'dashboard.topProducts': 'Top Products',
    'dashboard.recentSales': 'Recent Sales Activity',
    'dashboard.lowStockAlert': 'Low Stock Alert',
    'dashboard.lowStockMessage': 'items running low on stock.',
    'dashboard.viewInventory': 'View inventory',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addSale': 'Add Sale',
    'dashboard.addProduct': 'Add Product',
    'dashboard.scheduleStaff': 'Schedule Staff',
    'dashboard.viewReports': 'View Reports',
    'dashboard.noSalesData': 'No sales data available',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.unitsSold': 'units sold',
    'dashboard.sales': 'sales',
    
    // Sales
    'sales.title': 'Sales',
    'sales.subtitle': 'Manage your sales transactions and analyze performance',
    'sales.addSale': 'Add Sale',
    'sales.refreshData': 'Refresh Data',
    'sales.from': 'From:',
    'sales.to': 'To:',
    'sales.totalSales': 'Total Sales',
    'sales.totalRevenue': 'Total Revenue',
    'sales.averageSale': 'Average Sale',
    'sales.growthRate': 'Growth Rate',
    'sales.recentSales': 'Recent Sales',
    'sales.updating': 'Updating...',
    'sales.live': 'Live',
    'sales.date': 'Date',
    'sales.customer': 'Customer',
    'sales.items': 'Items',
    'sales.payment': 'Payment',
    'sales.total': 'Total',
    'sales.actions': 'Actions',
    'sales.walkInCustomer': 'Walk-in Customer',
    'sales.addNewSale': 'Add New Sale',
    'sales.customerName': 'Customer Name',
    'sales.customerEmail': 'Customer Email',
    'sales.optional': 'Optional',
    'sales.addItem': 'Add Item',
    'sales.productName': 'Product Name',
    'sales.quantity': 'Quantity',
    'sales.price': 'Price',
    'sales.taxAmount': 'Tax Amount',
    'sales.discount': 'Discount',
    'sales.paymentMethod': 'Payment Method',
    'sales.cash': 'Cash',
    'sales.creditCard': 'Credit Card',
    'sales.debitCard': 'Debit Card',
    'sales.mobilePayment': 'Mobile Payment',
    'sales.subtotal': 'Subtotal',
    'sales.tax': 'Tax',
    'sales.notes': 'Notes',
    'sales.notesPlaceholder': 'Optional notes about this sale...',
    'sales.cancel': 'Cancel',
    'sales.createSale': 'Create Sale',
    'sales.creating': 'Creating...',
    'sales.saleDetails': 'Sale Details',
    'sales.product': 'Product',
    'sales.qty': 'Qty',
    'sales.close': 'Close',
    
    // Assistant
    'assistant.title': 'AI Business Assistant',
    'assistant.subtitle': 'Ask me anything about your business',
    'assistant.welcome': 'Welcome to your AI Assistant!',
    'assistant.description': 'I can help you with sales analysis, inventory management, financial information and more.',
    'assistant.businessOverview': 'Business Overview',
    'assistant.revenue': 'Revenue',
    'assistant.netProfit': 'Net Profit',
    'assistant.topProduct': 'Top Product',
    'assistant.lowStockAlerts': 'Low Stock Alerts',
    'assistant.typing': 'Typing...',
    'assistant.inputPlaceholder': 'Ask me anything about your business...',
    'assistant.clearChat': 'Clear Chat',
    'assistant.suggestedQuestions': 'Suggested Questions',
    'assistant.businessInsights': 'Business Insights',
    'assistant.currentStatus': 'Current Status',
    'assistant.quickStats': 'Quick Stats',
    'assistant.todayRevenue': 'Today\'s Revenue',
    'assistant.activeEmployees': 'Active Employees',
    'assistant.lowStockProducts': 'Low Stock Products',
    'assistant.tips': 'Tips',
    'assistant.tipText': 'Try asking specific questions like "What is the best-selling product?" or "How can I improve profit margins?"',
    'assistant.failedToSend': 'Failed to send message',
    'assistant.failedToClear': 'Failed to clear chat history',
    'assistant.chatCleared': 'Chat history cleared',
    'assistant.topSellingProducts': 'What are the best-selling products?',
    'assistant.profitMargins': 'Show me the profit margins',
    'assistant.salesTrends': 'How are the sales trends?',
    'assistant.inventoryStatus': 'What is the current inventory status?',
    'assistant.employeeHours': 'How many hours did employees work?',
    'assistant.runPromotion': 'Should I run a promotion?',
    'assistant.salesAnalysis': 'Sales Analysis',
    'assistant.salesAnalysisDesc': 'View sales performance',
    'assistant.salesAnalysisQuestion': 'Show me the sales analysis',
    'assistant.financialOverview': 'Financial Overview',
    'assistant.financialOverviewDesc': 'Check your finances',
    'assistant.financialOverviewQuestion': 'Show me the financial overview',
    'assistant.inventoryCheck': 'Inventory Check',
    'assistant.inventoryCheckDesc': 'Inventory status',
    'assistant.inventoryCheckQuestion': 'Show me the inventory status',
    'assistant.employeeMetrics': 'Employee Metrics',
    'assistant.employeeMetricsDesc': 'Staff performance',
    'assistant.employeeMetricsQuestion': 'Show me the employee metrics',
    'assistant.suggestion1': 'What are the top products this month?',
    'assistant.suggestion2': 'How can I improve sales?',
    'assistant.suggestion3': 'What products need reordering?',
    'assistant.suggestion4': 'How is employee productivity?',
    'assistant.suggestion5': 'Do you suggest any marketing strategy?',
    'assistant.assistant': 'Assistant',
    'assistant.suggestions': 'Suggestions',
    'assistant.thisMonth': 'this month',
    'assistant.averageTransaction': 'Average Transaction',
    'assistant.salesRecommendation': 'I recommend focusing on the top product and increasing marketing for similar items.',
    'assistant.financialSummary': 'Financial Summary',
    'assistant.profitMargin': 'Profit Margin',
    'assistant.expenses': 'Expenses',
    'assistant.financialAdvice': 'Your finances look healthy. Consider investments for further growth.',
    'assistant.totalProducts': 'Total Products',
    'assistant.stockValue': 'Stock Value',
    'assistant.reorderSoon': 'Reorder Soon',
    'assistant.items': 'items',
    'assistant.inventoryAction': 'I recommend reordering low-stock items to avoid stockouts.',
    'assistant.employeeOverview': 'Employee Overview',
    'assistant.activeStaff': 'Active Staff',
    'assistant.hoursWorked': 'Hours Worked',
    'assistant.thisWeek': 'this week',
    'assistant.productivity': 'Productivity',
    'assistant.scheduleOptimization': 'Schedule Optimization',
    'assistant.excellent': 'Excellent',
    'assistant.employeeNote': 'Your staff has high productivity. Keep up the good practices.',
    'assistant.helpMessage': 'Hi! I\'m your AI business assistant. I can help you with various topics.',
    'assistant.capabilities': 'I can help you with',
    'assistant.cap1': 'Sales analysis and trends',
    'assistant.cap2': 'Financial overview and reports',
    'assistant.cap3': 'Inventory management',
    'assistant.cap4': 'Employee metrics and performance',
    'assistant.askMore': 'Ask me anything about your business!',
    'assistant.pendingOrders': 'Pending Orders',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.notes': 'Notes',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.businessName': 'Business Name',
    'auth.businessType': 'Business Type',
    'auth.createAccount': 'Create account',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.fullNameRequired': 'Full name is required',
    'auth.businessNameRequired': 'Business name is required',
    'auth.businessTypeRequired': 'Business type is required',
    'auth.invalidEmail': 'Invalid email address',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.selectBusinessType': 'Select business type',
    
    // Business Types
    'businessType.retail': 'Retail',
    'businessType.restaurant': 'Restaurant',
    'businessType.cafe': 'Cafe',
    'businessType.service': 'Service',
    'businessType.healthcare': 'Healthcare',
    'businessType.beauty': 'Beauty',
    'businessType.other': 'Other',
    
    // Header
    'header.title': 'BusinessPilot AI',
    'header.subtitle': 'Your all-in-one AI business operations team',
    'header.language': 'Language',
    'header.profile': 'Profile',
    'header.settings': 'Settings',
    
    // Time periods
    'time.7d': '7 days',
    'time.30d': '30 days',
    'time.90d': '90 days',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This week',
    'time.lastWeek': 'Last week',
    'time.thisMonth': 'This month',
    'time.lastMonth': 'Last month',
  }
};