import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'el' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('el'); // Greek as default

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation strings
const translations = {
  el: {
    // Navigation
    'nav.dashboard': 'Κεντρική Διαχείριση',
    'nav.sales': 'Πωλήσεις',
    'nav.inventory': 'Απόθεμα',
    'nav.employees': 'Υπάλληλοι',
    'nav.marketing': 'Μάρκετινγκ',
    'nav.finance': 'Οικονομικά',
    'nav.assistant': 'Βοηθός AI',
    'nav.paperwork': 'Γραφειοκρατία',
    
    // Dashboard
    'dashboard.title': 'Κεντρική Διαχείριση',
    'dashboard.totalSales': 'Συνολικές Πωλήσεις',
    'dashboard.revenue': 'Έσοδα',
    'dashboard.averageSale': 'Μέση Πώληση',
    'dashboard.growthRate': 'Ρυθμός Ανάπτυξης',
    'dashboard.topProducts': 'Κορυφαία Προϊόντα',
    'dashboard.recentSales': 'Πρόσφατη Δραστηριότητα Πωλήσεων',
    'dashboard.lowStockAlert': 'Ειδοποίηση Χαμηλού Αποθέματος',
    'dashboard.lowStockMessage': 'προϊόντα με χαμηλό απόθεμα.',
    'dashboard.viewInventory': 'Προβολή αποθέματος',
    'dashboard.quickActions': 'Γρήγορες Ενέργειες',
    'dashboard.addSale': 'Προσθήκη Πώλησης',
    'dashboard.addProduct': 'Προσθήκη Προϊόντος',
    'dashboard.scheduleStaff': 'Προγραμματισμός Προσωπικού',
    'dashboard.viewReports': 'Προβολή Αναφορών',
    'dashboard.noSalesData': 'Δεν υπάρχουν δεδομένα πωλήσεων',
    'dashboard.noRecentActivity': 'Δεν υπάρχει πρόσφατη δραστηριότητα',
    'dashboard.unitsSold': 'μονάδες πωλήθηκαν',
    'dashboard.sales': 'πωλήσεις',
    
    // Sales
    'sales.title': 'Πωλήσεις',
    'sales.subtitle': 'Διαχειριστείτε τις συναλλαγές πωλήσεων και αναλύστε την απόδοση',
    'sales.addSale': 'Προσθήκη Πώλησης',
    'sales.refreshData': 'Ανανέωση Δεδομένων',
    'sales.from': 'Από:',
    'sales.to': 'Έως:',
    'sales.totalSales': 'Συνολικές Πωλήσεις',
    'sales.totalRevenue': 'Συνολικά Έσοδα',
    'sales.averageSale': 'Μέση Πώληση',
    'sales.growthRate': 'Ρυθμός Ανάπτυξης',
    'sales.recentSales': 'Πρόσφατες Πωλήσεις',
    'sales.updating': 'Ενημέρωση...',
    'sales.live': 'Ζωντανά',
    'sales.date': 'Ημερομηνία',
    'sales.customer': 'Πελάτης',
    'sales.items': 'Αντικείμενα',
    'sales.payment': 'Πληρωμή',
    'sales.total': 'Σύνολο',
    'sales.actions': 'Ενέργειες',
    'sales.walkInCustomer': 'Πελάτης Χωρίς Ραντεβού',
    'sales.addNewSale': 'Προσθήκη Νέας Πώλησης',
    'sales.customerName': 'Όνομα Πελάτη',
    'sales.customerEmail': 'Email Πελάτη',
    'sales.optional': 'Προαιρετικό',
    'sales.addItem': 'Προσθήκη Αντικειμένου',
    'sales.productName': 'Όνομα Προϊόντος',
    'sales.quantity': 'Ποσότητα',
    'sales.price': 'Τιμή',
    'sales.taxAmount': 'Ποσό Φόρου',
    'sales.discount': 'Έκπτωση',
    'sales.paymentMethod': 'Μέθοδος Πληρωμής',
    'sales.cash': 'Μετρητά',
    'sales.creditCard': 'Πιστωτική Κάρτα',
    'sales.debitCard': 'Χρεωστική Κάρτα',
    'sales.mobilePayment': 'Κινητή Πληρωμή',
    'sales.subtotal': 'Υποσύνολο',
    'sales.tax': 'Φόρος',
    'sales.notes': 'Σημειώσεις',
    'sales.notesPlaceholder': 'Προαιρετικές σημειώσεις για αυτή την πώληση...',
    'sales.cancel': 'Ακύρωση',
    'sales.createSale': 'Δημιουργία Πώλησης',
    'sales.creating': 'Δημιουργία...',
    'sales.saleDetails': 'Λεπτομέρειες Πώλησης',
    'sales.product': 'Προϊόν',
    'sales.qty': 'Ποσ.',
    'sales.close': 'Κλείσιμο',
    
    // Common
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.save': 'Αποθήκευση',
    'common.cancel': 'Ακύρωση',
    'common.add': 'Προσθήκη',
    'common.edit': 'Επεξεργασία',
    'common.delete': 'Διαγραφή',
    'common.search': 'Αναζήτηση',
    'common.filter': 'Φίλτρο',
    'common.export': 'Εξαγωγή',
    'common.import': 'Εισαγωγή',
    'common.refresh': 'Ανανέωση',
    'common.back': 'Επιστροφή',
    'common.next': 'Επόμενο',
    'common.previous': 'Προηγούμενο',
    'common.close': 'Κλείσιμο',
    'common.submit': 'Υποβολή',
    'common.reset': 'Επαναφορά',
    'common.confirm': 'Επιβεβαίωση',
    'common.yes': 'Ναι',
    'common.no': 'Όχι',
    'common.name': 'Όνομα',
    'common.email': 'Email',
    'common.phone': 'Τηλέφωνο',
    'common.address': 'Διεύθυνση',
    'common.date': 'Ημερομηνία',
    'common.time': 'Ώρα',
    'common.status': 'Κατάσταση',
    'common.actions': 'Ενέργειες',
    'common.details': 'Λεπτομέρειες',
    'common.total': 'Σύνολο',
    'common.subtotal': 'Υποσύνολο',
    'common.price': 'Τιμή',
    'common.quantity': 'Ποσότητα',
    'common.category': 'Κατηγορία',
    'common.description': 'Περιγραφή',
    'common.notes': 'Σημειώσεις',
    
    // Authentication
    'auth.login': 'Σύνδεση',
    'auth.logout': 'Αποσύνδεση',
    'auth.register': 'Εγγραφή',
    'auth.signIn': 'Είσοδος',
    'auth.signUp': 'Εγγραφή',
    'auth.email': 'Email',
    'auth.password': 'Κωδικός',
    'auth.fullName': 'Πλήρες Όνομα',
    'auth.businessName': 'Όνομα Επιχείρησης',
    'auth.businessType': 'Τύπος Επιχείρησης',
    'auth.createAccount': 'Δημιουργία λογαριασμού',
    'auth.signingIn': 'Σύνδεση...',
    'auth.creatingAccount': 'Δημιουργία λογαριασμού...',
    'auth.emailRequired': 'Το email είναι υποχρεωτικό',
    'auth.passwordRequired': 'Ο κωδικός είναι υποχρεωτικός',
    'auth.fullNameRequired': 'Το πλήρες όνομα είναι υποχρεωτικό',
    'auth.businessNameRequired': 'Το όνομα επιχείρησης είναι υποχρεωτικό',
    'auth.businessTypeRequired': 'Ο τύπος επιχείρησης είναι υποχρεωτικός',
    'auth.invalidEmail': 'Μη έγκυρη διεύθυνση email',
    'auth.passwordMinLength': 'Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες',
    'auth.selectBusinessType': 'Επιλέξτε τύπο επιχείρησης',
    
    // Business Types
    'businessType.retail': 'Λιανικό Εμπόριο',
    'businessType.restaurant': 'Εστιατόριο',
    'businessType.cafe': 'Καφετέρια',
    'businessType.service': 'Υπηρεσίες',
    'businessType.healthcare': 'Υγειονομική Περίθαλψη',
    'businessType.beauty': 'Ομορφιά',
    'businessType.other': 'Άλλο',
    
    // Header
    'header.title': 'BusinessPilot AI',
    'header.subtitle': 'Η ολοκληρωμένη ομάδα AI για τις επιχειρησιακές σας δραστηριότητες',
    'header.language': 'Γλώσσα',
    'header.profile': 'Προφίλ',
    'header.settings': 'Ρυθμίσεις',
    
    // Time periods
    'time.7d': '7 ημέρες',
    'time.30d': '30 ημέρες',
    'time.90d': '90 ημέρες',
    'time.today': 'Σήμερα',
    'time.yesterday': 'Χθες',
    'time.thisWeek': 'Αυτή την εβδομάδα',
    'time.lastWeek': 'Την προηγούμενη εβδομάδα',
    'time.thisMonth': 'Αυτό το μήνα',
    'time.lastMonth': 'Τον προηγούμενο μήνα',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Central Management',
    'nav.sales': 'Sales',
    'nav.inventory': 'Inventory',
    'nav.employees': 'Employees',
    'nav.marketing': 'Marketing',
    'nav.finance': 'Finance',
    'nav.assistant': 'AI Assistant',
    'nav.paperwork': 'Paperwork',
    
    // Dashboard
    'dashboard.title': 'Central Management',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.revenue': 'Revenue',
    'dashboard.averageSale': 'Average Sale',
    'dashboard.growthRate': 'Growth Rate',
    'dashboard.topProducts': 'Top Products',
    'dashboard.recentSales': 'Recent Sales Activity',
    'dashboard.lowStockAlert': 'Low Stock Alert',
    'dashboard.lowStockMessage': 'items running low on stock.',
    'dashboard.viewInventory': 'View inventory',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addSale': 'Add Sale',
    'dashboard.addProduct': 'Add Product',
    'dashboard.scheduleStaff': 'Schedule Staff',
    'dashboard.viewReports': 'View Reports',
    'dashboard.noSalesData': 'No sales data available',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.unitsSold': 'units sold',
    'dashboard.sales': 'sales',
    
    // Sales
    'sales.title': 'Sales',
    'sales.subtitle': 'Manage your sales transactions and analyze performance',
    'sales.addSale': 'Add Sale',
    'sales.refreshData': 'Refresh Data',
    'sales.from': 'From:',
    'sales.to': 'To:',
    'sales.totalSales': 'Total Sales',
    'sales.totalRevenue': 'Total Revenue',
    'sales.averageSale': 'Average Sale',
    'sales.growthRate': 'Growth Rate',
    'sales.recentSales': 'Recent Sales',
    'sales.updating': 'Updating...',
    'sales.live': 'Live',
    'sales.date': 'Date',
    'sales.customer': 'Customer',
    'sales.items': 'Items',
    'sales.payment': 'Payment',
    'sales.total': 'Total',
    'sales.actions': 'Actions',
    'sales.walkInCustomer': 'Walk-in Customer',
    'sales.addNewSale': 'Add New Sale',
    'sales.customerName': 'Customer Name',
    'sales.customerEmail': 'Customer Email',
    'sales.optional': 'Optional',
    'sales.addItem': 'Add Item',
    'sales.productName': 'Product Name',
    'sales.quantity': 'Quantity',
    'sales.price': 'Price',
    'sales.taxAmount': 'Tax Amount',
    'sales.discount': 'Discount',
    'sales.paymentMethod': 'Payment Method',
    'sales.cash': 'Cash',
    'sales.creditCard': 'Credit Card',
    'sales.debitCard': 'Debit Card',
    'sales.mobilePayment': 'Mobile Payment',
    'sales.subtotal': 'Subtotal',
    'sales.tax': 'Tax',
    'sales.notes': 'Notes',
    'sales.notesPlaceholder': 'Optional notes about this sale...',
    'sales.cancel': 'Cancel',
    'sales.createSale': 'Create Sale',
    'sales.creating': 'Creating...',
    'sales.saleDetails': 'Sale Details',
    'sales.product': 'Product',
    'sales.qty': 'Qty',
    'sales.close': 'Close',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.notes': 'Notes',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.businessName': 'Business Name',
    'auth.businessType': 'Business Type',
    'auth.createAccount': 'Create account',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.fullNameRequired': 'Full name is required',
    'auth.businessNameRequired': 'Business name is required',
    'auth.businessTypeRequired': 'Business type is required',
    'auth.invalidEmail': 'Invalid email address',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.selectBusinessType': 'Select business type',
    
    // Business Types
    'businessType.retail': 'Retail',
    'businessType.restaurant': 'Restaurant',
    'businessType.cafe': 'Cafe',
    'businessType.service': 'Service',
    'businessType.healthcare': 'Healthcare',
    'businessType.beauty': 'Beauty',
    'businessType.other': 'Other',
    
    // Header
    'header.title': 'BusinessPilot AI',
    'header.subtitle': 'Your all-in-one AI business operations team',
    'header.language': 'Language',
    'header.profile': 'Profile',
    'header.settings': 'Settings',
    
    // Time periods
    'time.7d': '7 days',
    'time.30d': '30 days',
    'time.90d': '90 days',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This week',
    'time.lastWeek': 'Last week',
    'time.thisMonth': 'This month',
    'time.lastMonth': 'Last month',
  }
};